AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  PostTrackingFull:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::148849141066:role/service-role/Bitrix24Lambda'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: ANY
      Layers:
        - 'arn:aws:lambda:us-east-1:148849141066:layer:zeep:4'
